image:
  name: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Build and publish docker image to ECR.
        services:
          - docker
        script:
          # Define ECR repository URL as a variable
          - ECR_REPO="713315651054.dkr.ecr.us-east-2.amazonaws.com/profit-bank-java-micro-service"
          - $(aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin $ECR_REPO)
          - export IMAGE_NAME="$ECR_REPO:${BITBUCKET_BUILD_NUMBER}"
          - docker build -t "$IMAGE_NAME" .
          - docker tag "$IMAGE_NAME" "$IMAGE_NAME"
          - docker push "$IMAGE_NAME"
          
    - step:
        name: Deploy to ECS
        script:
          # Define ECR repository URL as a variable
          - ECR_REPO="713315651054.dkr.ecr.us-east-2.amazonaws.com/profit-bank-java-micro-service"
          
          # Use the same image name that was pushed to ECR.
          - export IMAGE_NAME="$ECR_REPO:${BITBUCKET_BUILD_NUMBER}"
          - envsubst < task-definition-template.json > task-definition.json
          - pipe: atlassian/aws-ecs-deploy:1.0.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              CLUSTER_NAME: 'your-cluster-name'
              SERVICE_NAME: 'your-service-name'
              TASK_DEFINITION: 'task-definition.json'